name: Test Package

on: [push, pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - run: ${{ secrets.NPM_TOKEN }} npm test
      - run: MAILGUN_KEY=${{ secrets.MAILGUN_KEY }} MAILGUN_DOMAIN=${{ secrets.MAILGUN_DOMAIN }} npm test
